# -*- coding: utf-8 -*-
"""PassNetwork_WhoScored.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voxWPzsiPkNXd6VS2yBVdeGuWENFHPSM
"""

pip install selenium beautifulsoup4 pandas numpy pydantic supabase mplsoccer adjustText networkx

"""

---



---



---

"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.colors import to_rgba, LinearSegmentedColormap, Normalize
from matplotlib.cm import ScalarMappable
from mplsoccer import Pitch, FontManager
import matplotlib.patheffects as path_effects
import networkx as nx
import json
import os

# =============================================================================
# 0. CONFIGURATION & THÈME
# =============================================================================

class ModernTheme:
    BACKGROUND = '#0e1117'
    PITCH_COLOR = '#0e1117'
    PITCH_LINES = '#2c3e50'

    PASS_HIGH = '#00ff85'
    PASS_MID = '#f1c40f'
    PASS_LOW = '#e74c3c'

    LINK_STRONG = '#00F2EA'
    LINK_WEAK = '#586069'

    PRIMARY = '#00F2EA'
    ACCENT = '#FFBE0B'

    TEXT_PRIMARY = '#FFFFFF'
    TEXT_SECONDARY = '#b0b3b8'
    TEXT_MUTED = '#586069'

    FONT_BOLD_URL = 'https://github.com/google/fonts/blob/main/apache/robotocondensed/RobotoCondensed-Bold.ttf?raw=true'
    FONT_REG_URL = 'https://github.com/google/fonts/blob/main/apache/robotocondensed/RobotoCondensed-Regular.ttf?raw=true'

# =============================================================================
# 1. CHARGEMENT ET TRAITEMENT
# =============================================================================

def parse_qualifiers(row):
    try:
        if pd.isna(row): return {}
        quals = json.loads(row) if isinstance(row, str) else row
        qual_dict = {}
        for q in quals:
            if 'type' in q and 'displayName' in q['type']:
                key = q['type']['displayName']
                value = q.get('value', True)
                qual_dict[key] = value
        return qual_dict
    except Exception:
        return {}

def load_and_process_data(events_path, players_path, target_team_id=None):
    events = pd.read_csv(events_path)
    players = pd.read_csv(players_path)

    if 'qualifiers' in events.columns:
        qual_data = events['qualifiers'].apply(parse_qualifiers).apply(pd.Series)
        events = pd.concat([events, qual_data], axis=1)

    players_renamed = players.rename(columns={
        'name': 'player_name',
        'shirt_no': 'jersey_number',
        'position': 'player_position',
        'id': 'player_id_key'
    })

    df = events.merge(players_renamed, left_on='player_id', right_on='player_id', how='left', suffixes=('', '_player'))

    team_col = next((col for col in df.columns if 'team' in col.lower() and 'id' in col.lower()), None)
    if not team_col: raise ValueError("Pas de colonne team_id trouvée.")

    sort_cols = [c for c in ['period_display_name', 'minute', 'second', 'id'] if c in df.columns]
    df = df.sort_values(by=sort_cols).reset_index(drop=True)

    df['next_player_id'] = df['player_id'].shift(-1)
    df['next_team_id'] = df[team_col].shift(-1)

    type_col = 'type_display_name' if 'type_display_name' in df.columns else 'type'
    outcome_col = 'outcome_type_display_name' if 'outcome_type_display_name' in df.columns else 'outcome'

    passes = df[
        (df[type_col] == 'Pass') &
        (df[outcome_col] == 'Successful') &
        (df[team_col] == df['next_team_id']) &
        (df['next_player_id'].notnull())
    ].copy()

    passes['recipient_id'] = passes['next_player_id']

    if target_team_id is None:
        target_team_id = passes[team_col].mode()[0]

    team_events = df[df[team_col] == target_team_id].copy()

    return passes[passes[team_col] == target_team_id], team_events, team_col

# =============================================================================
# 2. CALCUL DES MÉTRIQUES
# =============================================================================

def calculate_advanced_metrics(team_passes, team_events):
    agg_dict = {'x': 'mean', 'y': 'mean', 'id': 'count'}
    for col in ['player_name', 'jersey_number', 'player_position']:
        if col in team_passes.columns: agg_dict[col] = 'first'

    average_locs = team_passes.groupby('player_id').agg(agg_dict)
    average_locs.rename(columns={'id': 'successful_pass_count'}, inplace=True)

    type_col = 'type_display_name' if 'type_display_name' in team_events.columns else 'type'
    all_passes = team_events[team_events[type_col] == 'Pass'].groupby('player_id').size()
    average_locs['total_attempts'] = all_passes
    average_locs['pass_accuracy'] = (average_locs['successful_pass_count'] / average_locs['total_attempts'] * 100).fillna(0)

    pass_between = team_passes.groupby(['player_id', 'recipient_id']).agg({'id': 'count'}).reset_index()
    pass_between.rename(columns={'id': 'pass_count'}, inplace=True)

    G = nx.DiGraph()
    for _, row in pass_between.iterrows():
        G.add_edge(row['player_id'], row['recipient_id'], weight=row['pass_count'])

    try:
        average_locs['eigenvector_centrality'] = pd.Series(nx.eigenvector_centrality(G, weight='weight', max_iter=1000))
    except:
        average_locs['eigenvector_centrality'] = 0.1

    pass_between = pass_between.merge(average_locs[['x', 'y']], left_on='player_id', right_index=True)
    pass_between = pass_between.merge(average_locs[['x', 'y']], left_on='recipient_id', right_index=True, suffixes=('', '_end'))

    return average_locs, pass_between, G

# =============================================================================
# 3. MOTEUR DE VISUALISATION
# =============================================================================

def plot_professional_network(average_locs, pass_between, G, team_stats=None, match_info=None, analyzed_team_name="ÉQUIPE"):

    # --- Polices ---
    try:
        font_bold = FontManager(ModernTheme.FONT_BOLD_URL).prop
        font_reg = FontManager(ModernTheme.FONT_REG_URL).prop
    except:
        font_bold = None
        font_reg = None

    # --- Terrain ---
    pitch = Pitch(
        pitch_type='opta',
        pitch_color=ModernTheme.PITCH_COLOR,
        line_color=ModernTheme.PITCH_LINES,
        linewidth=1.5,
        goal_type='box',
        pad_top=4, pad_bottom=0.5, pad_left=0.5, pad_right=0.5
    )

    fig, ax = pitch.draw(figsize=(16, 12), constrained_layout=True)
    fig.set_facecolor(ModernTheme.BACKGROUND)

    # --- Colormap ---
    cmap_passes = LinearSegmentedColormap.from_list("PassAcc", [
        ModernTheme.PASS_LOW, ModernTheme.PASS_MID, ModernTheme.PASS_HIGH
    ])
    norm = Normalize(vmin=70, vmax=100)

    # --- Seuils ---
    max_passes_val = 0
    strong_thresh_val = 0

    # --- Tracé des Passes ---
    if not pass_between.empty:
        min_pass_threshold = 1
        pass_between = pass_between[pass_between['pass_count'] >= min_pass_threshold].copy()

        max_passes_val = pass_between['pass_count'].max()
        strong_thresh_val = int(max_passes_val * 0.8)

        pass_between = pass_between.sort_values('pass_count')

        for _, row in pass_between.iterrows():
            pass_strength = row['pass_count'] / max_passes_val
            width = (pass_strength ** 1.2) * 8 + 0.3
            alpha = max(0.15, (pass_strength ** 1.5) * 0.7 + 0.15)

            if pass_strength > 0.8:
                color_line = ModernTheme.LINK_STRONG
                z_ord = 2
            else:
                color_line = ModernTheme.LINK_WEAK
                z_ord = 1

            pitch.lines(
                row.x, row.y, row.x_end, row.y_end,
                lw=width, color=color_line, alpha=alpha,
                ax=ax, zorder=z_ord, capstyle='round'
            )

    # --- Tracé des Joueurs ---
    max_eigen = average_locs['eigenvector_centrality'].max()
    sizes = (average_locs['eigenvector_centrality'] / max_eigen * 2800) + 600

    starters = average_locs[average_locs['player_position'] != 'Sub']
    subs = average_locs[average_locs['player_position'] == 'Sub']

    def draw_nodes(nodes_df, marker_shape, is_sub=False):
        if nodes_df.empty: return
        node_sizes = sizes.loc[nodes_df.index]
        if is_sub: node_sizes = node_sizes * 0.7
        node_colors = nodes_df['pass_accuracy']

        # Glow
        pitch.scatter(nodes_df.x, nodes_df.y, s=node_sizes * 1.2, marker=marker_shape,
            c=ModernTheme.BACKGROUND, edgecolors=ModernTheme.TEXT_MUTED, linewidth=1, alpha=0.4, ax=ax, zorder=3)
        # Core
        pitch.scatter(nodes_df.x, nodes_df.y, s=node_sizes, marker=marker_shape,
            c=node_colors, cmap=cmap_passes, norm=norm, edgecolors='white', linewidth=2, alpha=1, ax=ax, zorder=4)

    draw_nodes(starters, marker_shape='o', is_sub=False)
    draw_nodes(subs, marker_shape='D', is_sub=True)

    # --- Annotations Joueurs ---
    txt_effects = [path_effects.Stroke(linewidth=4, foreground=ModernTheme.BACKGROUND), path_effects.Normal()]

    for player_id, row in average_locs.iterrows():
        is_sub = row.player_position == 'Sub'
        jersey = str(int(row.jersey_number)) if 'jersey_number' in row and not pd.isna(row.jersey_number) else ""
        text_color_inner = 'black' if row['pass_accuracy'] > 85 else 'white'

        pitch.annotate(jersey, xy=(row.x, row.y), ax=ax, zorder=6,
            va="center", ha="center", size=11 if is_sub else 13,
            color=text_color_inner, weight='bold', fontproperties=font_bold)

        name = str(row.player_name).split(" ")[-1].upper()
        if len(name) > 10: name = name[:9] + "."
        t = pitch.annotate(name, xy=(row.x, row.y - (4.5 if not is_sub else 4.0)), ax=ax, zorder=7,
            va="center", ha="center", size=9 if is_sub else 11, color='white', fontproperties=font_bold)
        t.set_path_effects(txt_effects)

    # --- EN-TÊTE DU MATCH ---
    if match_info:
        home_name = match_info.get('home_name', 'HOME').upper()
        away_name = match_info.get('away_name', 'AWAY').upper()
        score_text = f"{match_info.get('home_score', 0)} - {match_info.get('away_score', 0)}"

        text_y = 0.95
        logo_y = 0.915
        logo_dim = 0.07
        pivot_x = 0.25
        gap_from_score = 0.06

        def add_logo_to_fig(image_path, position_rect):
            if os.path.exists(image_path):
                try:
                    img = mpimg.imread(image_path)
                    logo_ax = fig.add_axes(position_rect, zorder=10)
                    logo_ax.imshow(img)
                    logo_ax.axis('off')
                except Exception as e:
                    print(f"Erreur logo: {e}")

        # Score
        fig.text(pivot_x, text_y, score_text, size=28, color='white', ha='center', va='center', fontproperties=font_bold)

        # Noms
        fig.text(pivot_x - gap_from_score, text_y, home_name, size=24, color='white', ha='right', va='center', fontproperties=font_bold)
        fig.text(pivot_x + gap_from_score, text_y, away_name, size=24, color='white', ha='left', va='center', fontproperties=font_bold)

        # Logos - bien espacés des noms
        add_logo_to_fig('Fulham.png', [0.03, logo_y, logo_dim, logo_dim])
        add_logo_to_fig('Man City.png', [0.42, logo_y, logo_dim, logo_dim])

        # Sous-titre
        fig.text(0.04, 0.88, f"ANALYSE : {analyzed_team_name.upper()}", size=14, color=ModernTheme.PRIMARY, fontproperties=font_reg)

    else:
        fig.text(0.02, 0.96, analyzed_team_name.upper(), size=30, color='white', ha='left', fontproperties=font_bold)

    # Colorbar
    cax = fig.add_axes([0.78, 0.03, 0.18, 0.02])
    cbar = plt.colorbar(ScalarMappable(norm=norm, cmap=cmap_passes), cax=cax, orientation='horizontal')
    cbar.ax.tick_params(labelsize=9, colors='white')
    cbar.outline.set_edgecolor(ModernTheme.TEXT_MUTED)
    fig.text(0.87, 0.06, "PRÉCISION DES PASSES (%)", ha='center', color='white', size=10, fontproperties=font_bold)

    # --- KPI STATS ---
    stats_label_y = 0.94
    stats_value_y = 0.915

    def add_stat_line(label, value, x_pos, color=ModernTheme.PRIMARY, is_name=False):
        fig.text(x_pos, stats_label_y, label, color=ModernTheme.TEXT_MUTED, size=9, fontproperties=font_reg, ha='center')
        size_val = 14 if is_name else 18
        fig.text(x_pos, stats_value_y, value, color=color, size=size_val, fontproperties=font_bold, ha='center')

    if team_stats:
        possession = f"{team_stats.get('possession_percentage', 0)}%"
        total_p = str(team_stats.get('total_passes', 0))
        success_p = str(team_stats.get('successful_passes', 0))
        acc_p = f"{team_stats.get('pass_accuracy', 0)}%"

        add_stat_line("POSSESSION", possession, 0.58, ModernTheme.PRIMARY)
        add_stat_line("TOTAL PASSES", total_p, 0.68, 'white')
        add_stat_line("PASSES RÉUSSIES", success_p, 0.78, ModernTheme.PASS_HIGH)
        add_stat_line("PRÉCISION", acc_p, 0.88, cmap_passes(norm(team_stats.get('pass_accuracy', 0))))

    # MENEUR DE JEU
    top_player = average_locs.sort_values('eigenvector_centrality', ascending=False).iloc[0]
    player_name = str(top_player.player_name).split(" ")[-1]
    add_stat_line("MENEUR DE JEU", player_name, 0.96, ModernTheme.ACCENT, is_name=True)

    # --- Légende ---
    legend_ax = fig.add_axes([0.02, 0.02, 0.60, 0.08])
    legend_ax.axis('off')
    legend_ax.set_xlim(0, 1)
    legend_ax.set_ylim(0, 1)

    legend_ax.scatter(0.04, 0.7, s=120, marker='o', c=ModernTheme.BACKGROUND, edgecolors='white', lw=2)
    legend_ax.text(0.07, 0.7, "Titulaire", color='white', va='center', size=10, fontproperties=font_reg)
    legend_ax.scatter(0.18, 0.7, s=100, marker='D', c=ModernTheme.BACKGROUND, edgecolors='white', lw=2)
    legend_ax.text(0.21, 0.7, "Remplaçant", color='white', va='center', size=10, fontproperties=font_reg)

    legend_ax.plot([0.33, 0.38], [0.7, 0.7], color=ModernTheme.LINK_WEAK, lw=2, alpha=0.6)
    legend_ax.text(0.39, 0.7, "Standard", color=ModernTheme.TEXT_SECONDARY, va='center', size=9, fontproperties=font_reg)

    legend_ax.plot([0.55, 0.60], [0.7, 0.7], color=ModernTheme.LINK_STRONG, lw=4)
    label_forte = f"Liaison Forte (>{strong_thresh_val} passes)"
    legend_ax.text(0.61, 0.7, label_forte, color=ModernTheme.PRIMARY, va='center', size=9, weight='bold', fontproperties=font_bold)

    legend_ax.text(0.04, 0.3, "TAILLE :", color=ModernTheme.ACCENT, size=9, fontproperties=font_bold)
    legend_ax.text(0.10, 0.3, "Influence", color='white', size=9, fontproperties=font_reg)
    legend_ax.text(0.40, 0.3, "COULEUR :", color=ModernTheme.PASS_HIGH, size=9, fontproperties=font_bold)
    legend_ax.text(0.48, 0.3, "Précision (%)", color='white', size=9, fontproperties=font_reg)

    return fig

# =============================================================================
# 4. EXÉCUTION AVEC EXPORT HAUTE QUALITÉ
# =============================================================================

if __name__ == "__main__":
    events_file = 'match_events_rows.csv'
    players_file = 'players_rows.csv'
    stats_file = 'team_match_stats.csv'
    matches_file = 'matches_rows.csv'

    try:
        print("📊 Chargement et analyse contextuelle...")

        stats_df = pd.read_csv(stats_file)
        matches_df = pd.read_csv(matches_file)

        team_mapping = dict(zip(stats_df.team_id, stats_df.team_name))

        match_data = matches_df.iloc[0]
        home_id = match_data['home_team_id']
        away_id = match_data['away_team_id']

        match_info = {
            'home_id': home_id,
            'away_id': away_id,
            'home_name': team_mapping.get(home_id, f"Team {home_id}"),
            'away_name': team_mapping.get(away_id, f"Team {away_id}"),
            'home_score': int(match_data['home_score']),
            'away_score': int(match_data['away_score'])
        }

        if match_info['home_name'] == 'Fulham' and match_info['home_score'] == 5:
             match_info['home_score'] = 4
             match_info['away_score'] = 5

        print(f"🏟️ Match : {match_info['home_name']} ({match_info['home_score']}) - ({match_info['away_score']}) {match_info['away_name']}")

        target_id = away_id
        analyzed_team_name = team_mapping.get(target_id, f"TEAM {target_id}")

        current_stats_df = stats_df[stats_df['team_id'] == target_id]
        stats_dict = current_stats_df.iloc[0].to_dict() if not current_stats_df.empty else {}

        passes_data, all_team_events, team_col = load_and_process_data(events_file, players_file, target_team_id=target_id)

        if not passes_data.empty:
            avg_locs, edges, graph = calculate_advanced_metrics(passes_data, all_team_events)

            fig = plot_professional_network(
                avg_locs,
                edges,
                graph,
                team_stats=stats_dict,
                match_info=match_info,
                analyzed_team_name=analyzed_team_name
            )

            # ========== EXPORT HAUTE QUALITÉ ==========
            output_filename = 'passing_network.png'
            print(f"\n💾 Sauvegarde en haute qualité...")

            fig.savefig(
                output_filename,
                dpi=300,  # 300 DPI = qualité impression professionnelle
                bbox_inches='tight',
                facecolor=fig.get_facecolor(),
                edgecolor='none',
                pad_inches=0.1
            )

            print(f"✅ Image HD sauvegardée : {output_filename}")
            print(f"   📐 Résolution : 300 DPI")
            print(f"   📁 Taille approximative : ~2-4 MB")

            # Optionnel : Export vectoriel (qualité infinie)
            vector_filename = 'passing_network_VECTOR.pdf'
            fig.savefig(
                vector_filename,
                format='pdf',
                bbox_inches='tight',
                facecolor=fig.get_facecolor(),
                edgecolor='none'
            )
            print(f"✅ Version vectorielle : {vector_filename} (zoom infini)")

            plt.show()
            print("\n🎉 Dashboard généré avec succès !")
        else:
            print("⚠️ Aucune donnée de passes trouvée.")

    except Exception as e:
        print(f"❌ Erreur critique : {e}")
        import traceback
        traceback.print_exc()